const CscData = [
    { classification:'결제/환불', id:'', category:'pay', title:'예약상품의 주문 취소는 언제까지 가능한가요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'결제/환불', id:'', category:'pay', title:'주문 내 상품을 일부 부분취소 할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'결제/환불', id:'', category:'pay', title:'결제 시 오류가 나타납니다.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'결제/환불', id:'', category:'pay', title:'선물하기로 주문을 하였는데, 받는 사람이 받지 않아요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'결제/환불', id:'', category:'pay', title:'결제를 완료하였는데, 재고가 없다는 알림과 함께 주문이 취소되었습니다.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'결제/환불', id:'', category:'pay', title:'결제 시 포인트를 사용한 경우, 환불 시 같이 돌려받을 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'결제/환불', id:'', category:'pay', title:'주문을 취소/반품하면 바로 환불 받을 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'교환/환불', id:'', category:'exchange', title:'교환 / 반품 요청을 하였는데, 요청을 취소하고 싶어요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'교환/환불', id:'', category:'exchange', title:'교환 / 반품 시, 어디로 상품을 발송하면 되나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'교환/환불', id:'', category:'exchange', title:'교환 / 반품하고 싶습니다. 어떻게 하면 되나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'교환/환불', id:'', category:'exchange', title:'다른 상품으로 교환할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'교환/환불', id:'', category:'exchange', title:'교환 / 반품이 불가능한 상품은 어떤 것이 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'쿠폰/포인트', id:'', category:'coupon', title:'적립된 포인트의 유효기간은 모두 동일한가요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'쿠폰/포인트', id:'', category:'coupon', title:'할인 및 기획전 상품의 경우 포인트는 어떻게 지급되나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'쿠폰/포인트', id:'', category:'coupon', title:'환불, 교환신청하면 쿠폰이나 포인트는 어떻게 되나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'쿠폰/포인트', id:'', category:'coupon', title:'쿠폰의 사용 기한을 연장해 주실 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'쿠폰/포인트', id:'', category:'coupon', title:'쿠폰 시리얼 번호를 받았습니다. 어디서 등록할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'쿠폰/포인트', id:'', category:'coupon', title:'쿠폰을 양도하고 싶습니다.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'쿠폰/포인트', id:'', category:'coupon', title:'결제 시 쿠폰을 사용한 경우, 환불 시 돌려받을 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'배송', id:'', category:'delivery', title:'상품이 파손된 상태로 배송되었습니다.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'배송', id:'', category:'delivery', title:'배송완료 상태인데, 상품을 받지 못했습니다.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'배송', id:'', category:'delivery', title:'주문 내 상품들을 각각 다른 배송지로 배송할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'배송', id:'', category:'delivery', title:'해외 배송을 받을 수 있을까요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'배송', id:'', category:'delivery', title:'택배 배송 외 수령 방법은 없나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'배송', id:'', category:'delivery', title:'상품을 수령했는데 주문의 배송완료처리가 되지 않았어요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'배송', id:'', category:'delivery', title:'반다이남코코리아몰의 배송비는 얼마인가요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'배송', id:'', category:'delivery', title:'교환 / 반품 배송비는 무료인가요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'A/S', id:'', category:'afterService', title:'A/S 기간에 대해 알고 싶어요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'A/S', id:'', category:'afterService', title:'프라모델을 구매 후 런너를 분실 / 파손 했습니다. A/S가 가능할까요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'A/S', id:'', category:'afterService', title:'A/S센터로 직접 방문해서 수리받을수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'A/S', id:'', category:'afterService', title:'A/S 기간이 종료된 경우, 해당 상품의 부품을 구할 수 없나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'A/S', id:'', category:'afterService', title:'반다이남코코리아몰에서 구매하지 않은 완구도 A/S를 받을 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'A/S', id:'', category:'afterService', title:'A/S 비용은 어떻게 입금하나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'A/S', id:'', category:'afterService', title:'외국에서 발매한 반다이의 완구 상품을 A/S 받을 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'A/S', id:'', category:'afterService', title:'A/S 처리 기간은 얼마나 걸리나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'상품관련', id:'', category:'product', title:'예약 상품의 출고 일정이 변동 되거나, 예약 주문이 취소 될 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'상품관련', id:'', category:'product', title:'사은품을 별도로 구매할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'상품관련', id:'', category:'product', title:'사은품을 다른 상품이나 포인트로 교환받고 싶습니다.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'상품관련', id:'', category:'product', title:'추첨 응모란 무엇인가요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'상품관련', id:'', category:'product', title:'예약 상품이란 무엇인가요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'상품관련', id:'', category:'product', title:'같은 상품인데 반다이남코코리아몰과 타 쇼핑몰와의 판매 가격이 다릅니다. 왜 그런가요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'상품관련', id:'', category:'product', title:'일본 반다이 발매 상품을 구매할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'상품관련', id:'', category:'product', title:'반다이남코코리아몰에서 판매하고 있는 상품을 건담베이스 매장에서도 구매할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'회원/개인정보', id:'', category:'personalInfo', title:'이전 달 회원등급 및 다음달 예상등급은 어떻게 확인하나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'회원/개인정보', id:'', category:'personalInfo', title:'친구나 가족의 계정을 양수하여 사용하고 싶습니다.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'회원/개인정보', id:'', category:'personalInfo', title:'개명으로 이름이 바뀌었습니다. 어떻게 하면 될까요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'회원/개인정보', id:'', category:'personalInfo', title:'계정 휴면의 기준에 대해 알고 싶습니다.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'회원/개인정보', id:'', category:'personalInfo', title:'마케팅 알림톡 / 이메일의 수신에 동의하였는데, 메세지나 메일이 오지 않아요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'회원/개인정보', id:'', category:'personalInfo', title:'마케팅 알림톡 / 이메일을 수신하고 싶지 않아요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'직영점 및 기타', id:'', category:'etc', title:'건담베이스의 정보를 알고 싶어요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'사이트 이용안내', id:'', category:'siteInfo', title:'선물하기 주문 시, 선물 메시지는 바로 받는 사람에게 전송되나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'사이트 이용안내', id:'', category:'siteInfo', title:'구매확정이란 무엇인가요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'사이트 이용안내', id:'', category:'siteInfo', title:'제 주문 내역을 확인하고 싶어요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'사이트 이용안내', id:'', category:'siteInfo', title:'주문한 상품을 다른 상품으로 변경하고 싶습니다. 변경할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'사이트 이용안내', id:'', category:'siteInfo', title:'비회원도 주문할 수 있나요?', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' },
    { classification:'사이트 이용안내', id:'', category:'siteInfo', title:'제가 작성한 상품 리뷰가 보이지 않아요.', detail:'죄송합니다. 주문 당 배송지를 한 군데로만 설정하실 수 있습니다.' }
]